list_products:
    path: /products
    controller: App\Product\Controller\ListProducts::handle

create_product:
    path: /products/create
    controller: App\Product\Controller\CreateProduct::handle
    methods: GET|POST

update_product:
    path: /products/update/{code}
    controller: App\Product\Controller\UpdateProduct::handle
    methods: GET|POST

view_product:
    path: /products/{code}
    controller: App\Product\Controller\ViewProduct::handle
    methods: GET

view_cart:
    path: /cart
    controller: App\ShoppingCart\Controller\ViewCart::handle
    methods: GET

cart_add_product:
    path: /cart/add/{code}
    controller: App\ShoppingCart\Controller\AddProduct::handle
    methods: POST
